In [1]:
import requests
import pandas as pd
import os 

print("Libraries imported successfully")

Libraries imported successfully

In [3]:
# Afg coordinates 

MIN_LAT = 29.0 # Southern Border 
MAX_LAT = 39.0 # Northern Border 
MIN_LON = 60.0 # Western Border 
MAX_LON = 75.0 # Eastern Border

# Earthquake from 1990-present 
START_DATE = "1990-01-01"
END_DATE = "2024-12-31"

# Only earthquakes magnitudes 4.0 and above 
MIN_MAGNITUDE = 4.0

print(f"Searching: Magnitude {MIN_MAGNITUDE}+ earthquakes")
print(f"Region: Afghanistan bounding box")
print(f"Period: {START_DATE} to {END_DATE}")

Searching: Magnitude 4.0+ earthquakes
Region: Afghanistan bounding box
Period: 1990-01-01 to 2024-12-31

In [4]:
# URL that asks USGS for earthquake date for our coordinates 

BASE_URL = "https://earthquake.usgs.gov/fdsnws/event/1/query"
params = {
    "format": "csv",          # get data as a CSV table
    "starttime": START_DATE,
    "endtime": END_DATE,
    "minlatitude": MIN_LAT,
    "maxlatitude": MAX_LAT,
    "minlongitude": MIN_LON,
    "maxlongitude": MAX_LON,
    "minmagnitude": MIN_MAGNITUDE,
    "orderby": "time"  
}

print("API parameters ready!")
print(f"URL will be: {BASE_URL}")

API parameters ready!
URL will be: https://earthquake.usgs.gov/fdsnws/event/1/query

In [6]:
print("Contacting USGS API... this may take 30-60 seconds")

response = requests.get(BASE_URL, params=params)

if response.status_code == 200:
    print(f"✅ Success! Data received from USGS")
    print(f"Data size: {len(response.content) / 1024:.1f} KB")
else:
    print(f"❌ Error: {response.status_code}")
    print(response.text)

Contacting USGS API... this may take 30-60 seconds
✅ Success! Data received from USGS
Data size: 1406.4 KB

In [8]:
import io 

df = pd.read_csv(io.StringIO(response.text))

os.makedirs("../data", exist_ok=True)
df.to_csv("../data/usgs_afghanistan_raw.csv", index=False)

print(f"✅ Dataset saved!")
print(f"Total earthquakes found: {len(df)}")
print(f"\nColumns in dataset:")
print(df.columns.tolist())
print(f"\nFirst 3 rows:")
df.head(3)

✅ Dataset saved!
Total earthquakes found: 8250

Columns in dataset:
['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst', 'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type', 'horizontalError', 'depthError', 'magError', 'magNst', 'status', 'locationSource', 'magSource']

First 3 rows:

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2024-12-30T21:48:54.605Z,36.7412,70.9153,224.419,4.0,mb,31.0,89.0,2.366,0.63,...,2025-03-08T22:39:13.040Z,"15 km SSE of Jurm, Afghanistan",earthquake,5.01,9.663,0.144,13.0,reviewed,us,us
1,2024-12-29T17:35:41.050Z,36.1980,70.6585,114.000,4.2,mb,57.0,92.0,2.091,1.05,...,2025-03-08T22:39:12.040Z,"75 km SSW of Jurm, Afghanistan",earthquake,7.38,8.300,0.089,35.0,reviewed,us,us
2,2024-12-29T16:47:55.254Z,36.5397,71.2467,223.091,4.0,mb,58.0,102.0,2.655,0.76,...,2025-03-08T22:39:12.040Z,"30 km WSW of Ashkāsham, Afghanistan",earthquake,7.40,9.264,0.078,44.0,reviewed,us,us

In [10]:
print("---Dataset Overview---")
print(f"Total earthquakes: {len(df)}")
print(f"Date range: {df['time'].min()} to {df['time'].max()}")
print(f"Magnitude range: {df['mag'].min()} to {df['mag'].max()}")
print(f"\nTop 5 largest earthquakes:")
df[['time', 'latitude', 'longitude', 'mag', 'depth', 'place']].sort_values('mag', ascending=False).head()

---Dataset Overview---
Total earthquakes: 8250
Date range: 1990-01-05T11:35:39.610Z to 2024-12-30T21:48:54.605Z
Magnitude range: 4.0 to 7.6

Top 5 largest earthquakes:

,time,latitude,longitude,mag,depth,place
5342,2005-10-08T03:50:40.800Z,34.5390,73.5880,7.6,26.0,"21 km NNE of Muzaffar?b?d, Pakistan"
2655,2015-10-26T09:09:42.560Z,36.5244,70.3676,7.5,231.0,"Hindu Kush region, Afghanistan"
6090,2002-03-03T12:08:19.740Z,36.5020,70.4820,7.4,225.6,"51 km SW of Jurm, Afghanistan"
2589,2015-12-07T07:50:05.950Z,38.2107,72.7797,7.2,22.0,"104 km W of Murghob, Tajikistan"
7095,1997-02-27T21:08:02.360Z,29.9760,68.2080,7.1,33.0,"29 km ESE of Harnai, Pakistan"